spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template1
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

telegram:
  bot:
    token: 6073198251:AAEaYWtDEhoYdk4678XfPNaAF42OUjjjJS8
    name: WordByHeartTestMaxBot
