# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../pgdata:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    links:
      - db
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:alpine
    command: redis-server --requirepass redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ../redisdata:/var/lib/redis
      - ./redis.config:/usr/local/etc/redis/redis.config
    environment:
      - REDIS_REPLICATION_MODE=master
