--liquibase formatted sql--changeset dakorshik:init word dataINSERT INTO public.word (eng, rus, dict_id) VALUES ('aquamarine', 'аквамарин', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('beige', 'бежевый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('snowy, snow-white', 'белоснежный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('white', 'белый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('turquoise', 'бирюзовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pale', 'бледный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('wine red, bordeaux, claret red', 'бордовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bronze', 'бронзовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('yellow green', 'желто-зеленый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('yellow', 'желтый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pearl', 'жемчужный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('green', 'зеленый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('goldenrod', 'золотистый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('gold, golden', 'золотой', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('emerald', 'изумрудный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('indigo', 'индиго', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('firebrick', 'кирпичный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('coral', 'коралловый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('brown', 'коричневый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('red', 'красный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cream', 'кремовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('azure', 'лазурный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lime green', 'лимонно-зеленый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lemon', 'лимонный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('salmon', 'лососевый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('raspberry', 'малиновый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('copper', 'медный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('honeydew', 'медовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('aqua', 'морская волна', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sky blue', 'небесно-голубой', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('olive', 'оливковый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('orange', 'оранжевый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sienna', 'охра', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ash', 'пепельно-серый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('peach, peachpuff', 'персиковый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sand-coloured', 'песочный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('purple', 'пурпурный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pink', 'розовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('light-green', 'салатовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('light', 'светлый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('silver, silvery', 'серебряный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('grey, gray', 'серый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('blue', 'синий', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lilac', 'сиреневый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('plum', 'сливовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ivory', 'слоновая кость', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('steel gray', 'стальной серый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('maroon', 'темно-бордовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('dark', 'темный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('navy (blue)', 'тёмно-синий', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('terracotta', 'терракотовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('dull', 'тусклый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('purple', 'фиолетовый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('violet', 'фиолетовый, темно-лиловый', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pistachio', 'фисташковый, зеленоватый цвет', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('magenta', 'фуксин', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fuchsia', 'фуксия', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('khaki, forest green', 'хаки', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('seagreen', 'цвет морской волны', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sea foam', 'цвет морской пены', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('black', 'черный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('amber', 'янтарный', 1);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('appearance', 'внешность', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('thin', 'худой', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fat', 'толстый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tall', 'высокий', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('short', 'невысокий', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('weak', 'слабый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('strong', 'сильный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('slim', 'стройный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('plump', 'полный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('skinny', 'тощий', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('old', 'старый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('young', 'молодой', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hairy', 'волосатый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bald', 'лысый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('curly', 'кудрявый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('straight', 'прямые', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pretty', 'красивая', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('handsome', 'красивый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ugly', 'уродливый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('character', 'характер', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('clever', 'умный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('talented', 'талантливый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('active', 'активный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('creative', 'творческий', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('energetic', 'энергичный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('stupid', 'глупый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('considerate', 'внимательный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cruel', 'жестокий', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('unkind', 'злой', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('polite', 'вежливый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('rude', 'грубый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('kind', 'добрый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tactful', 'тактичный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('married', 'женатый, замужняя', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('single', 'холостяк, незамужняя', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('generous', 'щедрый', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('greedy', 'жадный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('rich', 'богатый, состоятельный', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('poor', 'бедный, малоимущий', 2);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('action', 'действие', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('walk', 'идти, ходить', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('run', 'бежать, бегать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('march', 'маршировать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tiptoe', 'ходить на цыпочках', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('crawl', 'ползать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('drag', 'тянуть, тащить', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pull', 'тянуть, тащить', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('push', 'толкать; пихать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('jump', 'прыгать, скакать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('skip', 'прыгать, скакать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('leap', 'прыжок, скачок', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hop', 'подпрыгивать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hit', 'ударять (по чему-л.)', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('slap', 'шлепать, хлопать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('kick', 'удар ногой', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('stretch', 'тянуться, вытягиваться', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lift', 'поднятие, поднимать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('put', 'класть, ставить', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('chicken', 'курица', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lean', 'прислонять, опирать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('dive', 'нырять', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sit', 'сидеть; садиться', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('squat', 'приседание', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bend', 'сгибаться', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hold', 'держать; обнимать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('carry', 'нести, носить', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('catch', 'ловить; поймать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('throw', 'бросать, кидать', 3);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tool', 'инструмент', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hammer', 'молоток', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mallet', 'деревянный молоток', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('handsaw', 'ручная пила', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sandpaper', 'наждачная бумага', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('plane', 'рубанок', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('drill', 'дрель, перфоратор', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hacksaw', 'ножовка', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('vise', 'тиски', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('screwdriver', 'отвёртка', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('awl', 'шило', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('file', 'напильник', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('chisel', 'зубило', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('wrench', 'гаечный ключ', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pliers', 'плоскогубцы', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('scissors', 'ножницы', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pocketknife', 'многофункциональный нож', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('toolbox', 'инструментальный ящик', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('axe', 'топор', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('spade', 'лопата', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bucket', 'ведро', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ladder', 'лестница (приставная)', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('stepladder', 'стремянка', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('nail', 'гвоздь', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('screw', 'винт, шуруп', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bolt', 'болт', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('nut', 'гайка', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('washer', 'шайба', 4);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tableware', 'посуда', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('plate', 'тарелка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bowl', 'миска', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cup', 'чашка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mug', 'кружка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('spoon', 'ложка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fork', 'вилка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('knife', 'нож', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('glass', 'стакан', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('saucepan', 'кастрюля', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lid', 'крышка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ladle', 'черпак', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('jug', 'кувшин', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('kettle', 'чайник', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('coffeepot', 'кофейник', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('teapot', 'чайник (для заварки)', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('frying pan', 'сковорода с ручкой', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pan', 'сковорода', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('salt shaker', 'солонка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pepper shaker', 'перечница', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sugar bowl', 'сахарница', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bottle', 'бутылка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('napkin', 'салфетка', 5);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('emotion', 'эмоция', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mischievous', 'озорной, непослушный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ecstatic', 'восторженный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('content', 'довольный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bored', 'скучающий', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('shocked', 'в состоянии шока', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('offended', 'обиженный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('confident', 'самоуверенный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('happy', 'счастливый', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hopeful', 'надеющийся', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('curious', 'любопытный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('excited', 'взволнованный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lonely', 'одинокий', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('nervous', 'нервный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('goofy', 'бестолковый, глупый', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('scared', 'испуганный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sad', 'грустный, печальный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hungry', 'голодный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('thirsty', 'испытывающий жажду', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tired', 'уставший', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sleepy', 'сонный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('surprised', 'удивленный', 6);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bedroom', 'спальня', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bed', 'кровать, постель', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mattress', 'матрац', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pillow', 'подушка', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pillowcase', 'наволочка', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sheet', 'простыня', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('blanket', 'одеяло', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bedspread', 'постельное покрывало', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('duvet', 'пуховое одеяло', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('quilt', 'лоскутное одеяло', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('nightstand', 'тумбочка', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('alarm clock', 'будильник', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('dresser', 'комод с зеркалом', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mirror', 'зеркало', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('curtain', 'занавеска', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('window', 'окно', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('carpet', 'ковёр', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('picture', 'картина; рисунок', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('casket', 'шкатулка', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('door', 'дверь', 7);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bird', 'птица', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('robin', 'дрозд', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('jay', 'сойка', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hummingbird', 'колибри', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pheasant', 'фазан', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('crow', 'ворона, ворон', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('flamingo', 'фламинго', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('seagull', 'чайка', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sparrow', 'воробей', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('woodpecker', 'дятел', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('swallow', 'ласточка', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pigeon', 'голубь', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('owl', 'сова, филин', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hawk', 'сокол', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('eagle', 'орел', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('canary', 'канарейка', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cuckoo', 'кукушка', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cockatoo', 'какаду', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('parrot', 'попугай', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('parakeet', 'попугай', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('duck', 'утка', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('goose', 'гусь', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('swan', 'лебедь', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('crane', 'журавль, цапля', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('stork', 'аист', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pelican', 'пеликан', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('peacock', 'павлин', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('penguin', 'пингвин', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ostrich', 'страус', 8);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sport', 'спорт', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('football', 'футбол', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('soccer', 'футбол', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('basketball', 'баскетбол', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('volleyball', 'волейбол', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('baseball', 'бейсбол', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hockey', 'хоккей', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('badminton', 'бадминтон', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tennis', 'теннис', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('rugby', 'регби', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('golf', 'гольф', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('billiards', 'бильярд', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('swimming', 'плавание', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('biathlon', 'биатлон', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('wrestling', 'борьба', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('gymnastics', 'гимнастика', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fencing', 'фехтование', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('race', 'гонка', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('polo', 'поло', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bowling', 'боулинг', 9);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('drink', 'напиток, пить', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('soft drink', 'безалкогольный напиток', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('beverage', 'напиток', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('water', 'вода', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lemonade', 'лимонад', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tea', 'чай', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('coffee', 'кофе', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('juice', 'сок', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('milk', 'молоко', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cocoa', 'какао', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('chocolate', 'горячий шоколад', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('cocktail', 'коктейль', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('milkshake', 'молочный коктейль', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('iced tea', 'холодный чай', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('orange juice', 'апельсиновый сок', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tomato juice', 'томатный сок', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fruit juice', 'фруктовый сок', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('vegetable juice', 'овощной сок', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('alcohol', 'алкоголь, спирт', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('alcoholic beverage', 'алкогольные напитки', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('beer', 'пиво', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('wine', 'вино', 10);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bathroom', 'ванная комната', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('toilet', 'унитаз, туалет', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('restroom', 'уборная, туалет', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('freshener', 'освежающее средство, освежитель', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('towel', 'полотенце', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hamper', 'корзина с крышкой', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('scale', 'весы', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('shelf', 'полка', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fan', 'фен', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mirror', 'зеркало', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sink', 'раковина', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bath', 'ванна', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('toothbrush', 'зубная щётка', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('toothpaste', 'зубная паста', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('soap', 'мыло', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('shower', 'душ', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sponge', 'губка', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('comb', 'расчёска', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('razor', 'бритва, брить', 11);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('piece', 'монета', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('coin', 'монета', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('one p coin', '1 пенс', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a penny', '1 пенс', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('twopence', '2 пенса', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a twopenny', '2 пенса', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a fivepenny piece', '5 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('five p', '5 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a tenpenny piece', '10 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ten p', '10 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a twenty pence coin', '20 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('twenty p', '20 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a fifty pence piece', '50 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fifty p', '50 пенсов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a pound', '1 фунт', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('quid', 'соверен, фунт (стерлингов)', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('five pounds (quid)', '5 фунтов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a fiver', '5 фунтов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ten pounds (quid)', '10 фунтов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a tenner', '10 фунтов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('twenty pounds (quid)', '20 фунтов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fifty pounds (quid)', '50 фунтов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('one cent', '1 цент', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a penny', '1 цент', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('five cents', '5 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a nickel', '5 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ten cents', '10 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a dime', '10 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('twenty-five cents', '25 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a quarter', '25 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('a half-dollar', '50 центов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('one dollar', '1 доллар', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('two dollar', '2 доллара', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('five dollar', '5 долларов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ten dollar', '10 долларов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('twenty dollar', '20 долларов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('fifty dollar', '50 долларов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hundred dollar', '100 долларов', 12);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('house', 'дом', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('apartment', 'квартира', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('room', 'комната; помещение', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bathroom', 'ванная комната', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('balcony', 'балкон', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bedroom', 'спальня', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('closet', 'шкаф', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('dining room', 'столовая', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('doorbell', 'дверной звонок', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('door', 'дверь', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('upstairs', 'верхний этаж', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('downstairs', 'подвальный этаж', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('roof', 'крыша, кровля', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('window', 'окно', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('garage', 'гараж', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hall', 'зал', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('kitchen', 'кухня', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('hallway', 'коридор', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('living room', 'гостиная', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mailbox', 'почтовый ящик', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('shower', 'душ', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('stairs', 'лестница', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('toilet', 'туалет, унитаз', 13);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('school', 'школа', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('backpack', 'рюкзак', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('blackboard', 'классная доска', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('chair', 'стул', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('chalk', 'мел', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('classroom', 'класс', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('clock', 'часы', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('desk', 'парта', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('eraser', 'ластик', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('glue', 'клей', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('locker', 'запирающийся шкафчик', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('marker', 'маркер', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pen', 'ручка', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pencil', 'карандаш', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pencil case', 'пенал', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('sharpener', 'точилка', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('ruler', 'линейка', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('globe', 'глобус', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('map', 'карта', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('scissors', 'ножницы', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('tape', 'клейкая лента', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('teacher', 'учитель', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('headmaster', 'директор школы', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('pupil', 'ученик', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('student', 'студент', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('textbook', 'учебник', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('notebook', 'тетрадь', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('paper', 'бумага', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('lesson', 'урок, занятие', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('geography', 'география', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('biology', 'биология', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('chemistry', 'химия', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('history', 'история', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mathematics', 'математика', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('physics', 'физика', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('music', 'музыка', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('drawing', 'рисование', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('bell', 'звонок', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('break', 'перемена', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('education', 'образование', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('curriculum', 'учебный план', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('examination', 'экзамен', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('exam', 'экзамен', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('mark', 'оценка', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('test', 'контрольная работа', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('semester', 'семестр', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('timetable', 'расписание', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('holiday', 'каникулы', 14);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('geography', 'география', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('United States (of America)', 'Соединённые Штаты (Америки)', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Canada', 'Канада', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Mexico', 'Мексика', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Panama', 'Панама', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Haiti', 'Гаити', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Jamaica', 'Ямайка', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Peru', 'Перу', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Dominican Republic', 'Доминиканская Республика', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Cuba', 'Куба', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Caribbean', 'Карибы', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Greenland', 'Гренландия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('El Salvador', 'Сальвадор', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Puerto Rico', 'Пуэрто-Рико', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Colombia', 'Колумбия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Venezuela', 'Венесуэла', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Honduras', 'Гондурас', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Guyana', 'Гайана', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Guatemala', 'Гватемала', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Bolivia', 'Боливия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Argentina', 'Аргентина', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Ecuador', 'Эквадор', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Chile', 'Чили', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Brazil', 'Бразилия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Costa Rica', 'Коста-Рика', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Scotland', 'Шотландия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Albania', 'Албания', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Ireland', 'Ирландия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Russia', 'Россия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Oman', 'Оман', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Bulgaria', 'Болгария', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Saudi Arabia', 'Саудовская Аравия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Hungary', 'Венгрия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Cyprus', 'Кипр', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Iraq', 'Ирак', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Iran', 'Иран', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Syria', 'Сирия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Lebanon', 'Ливан', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Israel', 'Израиль', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Jordan', 'Иордания', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Yemen', 'Йемен', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Kuwait', 'Кувейт', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Bahrain', 'Бахрейн', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Netherlands', 'Нидерланды', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Luxembourg', 'Люксембург', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Belgium', 'Бельгия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Portugal', 'Португалия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('France', 'Франция', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('England', 'Англия', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Denmark', 'Дания', 15);
INSERT INTO public.word (eng, rus, dict_id) VALUES ('Spain', 'Испания', 15);
